version: '3.8'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  web:
    build: .
    command: fastapi run server.py
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - worker
      - rabbitmq
    env_file:
      - .env

  worker:
    build: .
    command: celery -A tasks worker --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: "redis"
    ports:
      - "6379:6379"
